server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/learnspringsecurity
    username: postgres
    password: admin

  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect